<?php
/**
 * Orange Management
 *
 * PHP Version 7.1
 *
 * @category   TBD
 * @package    TBD
 * @copyright  Dennis Eichhorn
 * @license    OMS License 1.0
 * @version    1.0.0
 * @link       http://website.orange-management.de
 */
declare(strict_types = 1);

namespace phpOMS\Utils\RnG;

/**
 * Name generator.
 *
 * @category   Framework
 * @package    Utils\RnG
 * @license    OMS License 1.0
 * @link       http://website.orange-management.de
 * @since      1.0.0
 */
class Name
{
    private static $names = [
        'western' => [
            'female' => [
                'Aaliyah', 'Cece', 'Heidi', 'Lilly', 'Rebekah', 'Aarushi', 'Cecelia', 'Helen', 'Lily', 'Reese',
                'Abagail', 'Cecilia', 'Helena', 'Lina', 'Regan', 'Abbey', 'Cecily', 'Helene', 'Linda', 'Regina', 'Abbi',
                'Celeste', 'Helga', 'Lindsay', 'Reilly', 'Abbie', 'Celestia', 'Helina', 'Lindsey', 'Reina', 'Abby',
                'Celestine', 'Henrietta', 'Lindy', 'Remi', 'Abi', 'Celia', 'Hepsiba', 'Lisa', 'Rena', 'Abia', 'Celina',
                'Hera', 'Lisette', 'Renata', 'Abigail', 'Celine', 'Hermione', 'Liv', 'Rene', 'Abrianna', 'Celise',
                'Hester', 'Livia', 'Renee', 'Abrielle', 'Cerise', 'Hetty', 'Livvy', 'Renesmee', 'Aby', 'Cerys',
                'Hilary', 'Liz', 'Reyna', 'Acacia', 'Chanel', 'Hilda', 'Liza', 'Rhea', 'Ada', 'Chanelle', 'Hillary',
                'Lizbeth', 'Rhian', 'Adalia', 'Chantal', 'Hollie', 'Lizette', 'Rhianna', 'Adalyn', 'Chantelle', 'Holly',
                'Lizzie', 'Rhiannon', 'Addie', 'Charis', 'Honesty', 'Lizzy', 'Rhoda', 'Addison', 'Charissa', 'Honey',
                'Logan', 'Rhona', 'Adelaide', 'Charity', 'Honor', 'Lois', 'Rhonda', 'Adele', 'Charlene', 'Honour',
                'Lola', 'Ria', 'Adelene', 'Charley', 'Hope', 'Lolita', 'Rianna', 'Adelia', 'Charlie', 'Hyacinth',
                'London', 'Ricki', 'Adelina', 'Charlize', 'Ianthe', 'Lora', 'Rihanna', 'Adeline', 'Charlotte', 'Ida',
                'Loran', 'Rikki', 'Adreanna', 'Charmaine', 'Ila', 'Lorelei', 'Riley', 'Adriana', 'Chastity', 'Ilene',
                'Loren', 'Rita', 'Adrianna', 'Chelsea', 'Iliana', 'Lorena', 'River', 'Adrianne', 'Chelsey', 'Ilona',
                'Loretta', 'Riya', 'Adrienne', 'Chenai', 'Ilse', 'Lori', 'Roanne', 'Aerona', 'Chenille', 'Imani',
                'Lorie', 'Roberta', 'Agatha', 'Cher', 'Imelda', 'Lorna', 'Robin', 'Aggie', 'Cheri', 'Imogen',
                'Lorraine', 'Robyn', 'Agnes', 'Cherie', 'India', 'Lorri', 'Rochelle', 'Aida', 'Cherry', 'Indie',
                'Lorrie', 'Rocio', 'Aileen', 'Cheryl', 'Indigo', 'Lottie', 'Roisin', 'Ailsa', 'Cheyanne', 'Indira',
                'Lotus', 'Rolanda', 'Aimee', 'Cheyenne', 'Ines', 'Lou', 'Ronda', 'Aine', 'Chiara', 'Ingrid', 'Louella',
                'Roni', 'Ainsleigh', 'Chloe', 'Iona', 'Louisa', 'Rosa', 'Ainsley', 'Chris', 'Ira', 'Louise', 'Rosalie',
                'Aisha', 'Chrissy', 'Irene', 'Luann', 'Rosalina', 'Aisling', 'Christa', 'Irina', 'Lucia', 'Rosalind',
                'Aislinn', 'Christabel', 'Iris', 'Luciana', 'Rosalinda', 'Alaina', 'Christal', 'Irma', 'Lucie',
                'Rosalynn', 'Alana', 'Christen', 'Isa', 'Lucille', 'Rosanna', 'Alanis', 'Christi', 'Isabel', 'Lucinda',
                'Rose', 'Alanna', 'Christiana', 'Isabell', 'Lucky', 'Roseanne', 'Alannah', 'Christie', 'Isabella',
                'Lucy', 'Rosella', 'Alaska', 'Christina', 'Isabelle', 'Luisa', 'Rosemarie', 'Alayah', 'Christine',
                'Isadora', 'Lulu', 'Rosemary', 'Alayna', 'Christy', 'Isha', 'Luna', 'Rosetta', 'Alba', 'Chrystal',
                'Isis', 'Lupita', 'Rosie', 'Alberta', 'Ciara', 'Isla', 'Luz', 'Rosy', 'Aleah', 'Cici', 'Isobel',
                'Lydia', 'Rowan', 'Alecia', 'Ciel', 'Isolde', 'Lyla', 'Rowena', 'Aleisha', 'Cierra', 'Itzel', 'Lynda',
                'Roxana', 'Alejandra', 'Cindy', 'Ivana', 'Lyndsey', 'Roxanne', 'Alena', 'Claire', 'Ivy', 'Lynette',
                'Roxie', 'Alessandra', 'Clara', 'Iyanna', 'Lynn', 'Roxy', 'Alessia', 'Clarabelle', 'Izabella', 'Lynne',
                'Rozlynn', 'Alex', 'Clare', 'Izidora', 'Lynnette', 'Ruby', 'Alexa', 'Clarice', 'Izzie', 'Lynsey', 'Rue',
                'Alexandra', 'Claris', 'Izzy', 'Lyra', 'Ruth', 'Alexandria', 'Clarissa', 'Jacinda', 'Lyric', 'Ruthie',
                'Alexia', 'Clarisse', 'Jacinta', 'Mabel', 'Ryanne', 'Alexis', 'Clarity', 'Jackie', 'Macey', 'Rydel',
                'Alexus', 'Clary', 'Jacqueline', 'Macie', 'Rylee', 'Ali', 'Claudette', 'Jacquelyn', 'Mackenzie',
                'Ryleigh', 'Alia', 'Claudia', 'Jada', 'Macy', 'Rylie', 'Alice', 'Claudine', 'Jade', 'Madalyn', 'Sabina',
                'Alicia', 'Clea', 'Jaden', 'Maddie', 'Sabine', 'Alina', 'Clementine', 'Jadyn', 'Maddison', 'Sable',
                'Alisa', 'Cleo', 'Jaelynn', 'Maddy', 'Sabrina', 'Alisha', 'Cleopatra', 'Jaida', 'Madeleine', 'Sade',
                'Alison', 'Clodagh', 'Jaime', 'Madeline', 'Sadhbh', 'Alissa', 'Clotilde', 'Jamie', 'Madelyn', 'Sadie',
                'Alivia', 'Clover', 'Jamiya', 'Madison', 'Saffron', 'Aliyah', 'Coco', 'Jan', 'Madisyn', 'Safire',
                'Aliza', 'Colette', 'Jana', 'Madonna', 'Safiya', 'Alize', 'Colleen', 'Jancis', 'Madyson', 'Sage',
                'Alka', 'Connie', 'Jane', 'Mae', 'Sahara', 'Allie', 'Constance', 'Janelle', 'Maeve', 'Saige', 'Allison',
                'Cora', 'Janessa', 'Magda', 'Saira', 'Ally', 'Coral', 'Janet', 'Magdalena', 'Sally', 'Allyson',
                'Coralie', 'Janette', 'Magdalene', 'Salma', 'Alma', 'Coraline', 'Jania', 'Maggie', 'Salome', 'Alondra',
                'Cordelia', 'Janice', 'Maia', 'Sam', 'Alycia', 'Cori', 'Janie', 'Maire', 'Samantha', 'Alyshialynn',
                'Corina', 'Janine', 'Mairead', 'Samara', 'Alyson', 'Corinne', 'Janis', 'Maisie', 'Samia', 'Alyssa',
                'Cornelia', 'Janiya', 'Maisy', 'Samira', 'Alyssia', 'Corra', 'January', 'Maja', 'Sammie', 'Amalia',
                'Cosette', 'Jaqueline', 'Makayla', 'Sammy', 'Amanda', 'Courtney', 'Jasmin', 'Makenna', 'Sandra',
                'Amani', 'Cressida', 'Jasmine', 'Makenzie', 'Sandy', 'Amara', 'Cristal', 'Jaya', 'Malia', 'Sania',
                'Amari', 'Cristina', 'Jayda', 'Malina', 'Saoirse', 'Amaris', 'Crystal', 'Jayden', 'Malinda', 'Sapphire',
                'Amaya', 'Cyndi', 'Jayla', 'Mallory', 'Sara', 'Amber', 'Cynthia', 'Jaylene', 'Malory', 'Sarah',
                'Amberly', 'Dagmar', 'Jaylinn', 'Mandy', 'Sarina', 'Amelia', 'Dahlia', 'Jaylynn', 'Manuela', 'Sariya',
                'Amelie', 'Daisy', 'Jayne', 'Mara', 'Sascha', 'America', 'Dakota', 'Jazlyn', 'Marcela', 'Sasha',
                'Amethyst', 'Dana', 'Jazmin', 'Marcella', 'Saskia', 'Amie', 'Danette', 'Jazmine', 'Marcelle', 'Savanna',
                'Amina', 'Dani', 'Jazz', 'Marci', 'Savannah', 'Amirah', 'Danica', 'Jean', 'Marcia', 'Scarlet', 'Amity',
                'Daniela', 'Jeanette', 'Marcie', 'Scarlett', 'Amy', 'Daniella', 'Jeanine', 'Marcy', 'Sebastianne',
                'Amya', 'Danielle', 'Jeanne', 'Margaret', 'Selah', 'Ana', 'Danika', 'Jeannette', 'Margarita', 'Selena',
                'Anabel', 'Daphne', 'Jeannie', 'Margaux', 'Selene', 'Anabelle', 'Dara', 'Jeannine', 'Marge', 'Selina',
                'Anahi', 'Darby', 'Jemima', 'Margie', 'Selma', 'Anais', 'Darcey', 'Jemma', 'Margo', 'Senuri',
                'Anamaria', 'Darcie', 'Jen', 'Margot', 'September', 'Ananya', 'Darcy', 'Jena', 'Margret', 'Seren',
                'Anastasia', 'Daria', 'Jenelle', 'Maria', 'Serena', 'Andie', 'Darla', 'Jenessa', 'Mariah', 'Serenity',
                'Andrea', 'Darlene', 'Jenna', 'Mariam', 'Shakira', 'Andromeda', 'Dasia', 'Jennette', 'Marian', 'Shana',
                'Angel', 'Davida', 'Jenni', 'Mariana', 'Shania', 'Angela', 'Davina', 'Jennie', 'Marianna', 'Shannon',
                'Angelia', 'Dawn', 'Jennifer', 'Marianne', 'Shari', 'Angelica', 'Dayna', 'Jenny', 'Maribel', 'Sharon',
                'Angelina', 'Daysha', 'Jensen', 'Marie', 'Shary', 'Angeline', 'Deana', 'Jeri', 'Mariela', 'Shauna',
                'Angelique', 'Deandra', 'Jerri', 'Mariella', 'Shawn', 'Angie', 'Deann', 'Jess', 'Marilyn', 'Shawna',
                'Anika', 'Deanna', 'Jessa', 'Marina', 'Shawnette', 'Anisa', 'Deanne', 'Jessica', 'Marion', 'Shayla',
                'Anita', 'Deb', 'Jessie', 'Marisa', 'Shayna', 'Aniya', 'Debbie', 'Jet', 'Marisol', 'Shea', 'Aniyah',
                'Debby', 'Jewel', 'Marissa', 'Sheba', 'Anjali', 'Debora', 'Jill', 'Maritza', 'Sheena', 'Ann', 'Deborah',
                'Jillian', 'Marjorie', 'Sheila', 'Anna', 'Debra', 'Jo', 'Marla', 'Shelby', 'Annabel', 'Dee', 'Joan',
                'Marlee', 'Shelia', 'Annabella', 'Deedee', 'Joann', 'Marlena', 'Shelley', 'Annabelle', 'Deena',
                'Joanna', 'Marlene', 'Shelly', 'Annabeth', 'Deidre', 'Joanne', 'Marley', 'Sheri', 'Annalisa', 'Deirdre',
                'Jocelyn', 'Marnie', 'Sheridan', 'Annalise', 'Deja', 'Jodi', 'Marsha', 'Sherri', 'Anne', 'Delaney',
                'Jodie', 'Martha', 'Sherrie', 'Anneke', 'Delanie', 'Jody', 'Martina', 'Sherry', 'Annemarie', 'Delany',
                'Joelle', 'Mary', 'Sheryl', 'Annette', 'Delia', 'Johanna', 'Maryam', 'Shirley', 'Annie', 'Delilah',
                'Joleen', 'Maryann', 'Shivani', 'Annika', 'Della', 'Jolene', 'Marybeth', 'Shona', 'Annmarie', 'Delores',
                'Jolie', 'Masie', 'Shonagh', 'Anthea', 'Delphine', 'Joni', 'Matilda', 'Shreya', 'Antoinette',
                'Demetria', 'Jordan', 'Maude', 'Shyla', 'Antonia', 'Demi', 'Jordana', 'Maura', 'Sian', 'Anuja', 'Dena',
                'Jordyn', 'Maureen', 'Sidney', 'Anusha', 'Denise', 'Jorja', 'Mavis', 'Sienna', 'Anushka', 'Denny',
                'Joselyn', 'Maxime', 'Sierra', 'Anya', 'Desiree', 'Josephine', 'Maxine', 'Sigourney', 'Aoibhe',
                'Destinee', 'Josie', 'May', 'Silvia', 'Aoibheann', 'Destiny', 'Journey', 'Maya', 'Simone', 'Aoife',
                'Diamond', 'Joy', 'Mazie', 'Simran', 'Aphrodite', 'Diana', 'Joyce', 'Mckayla', 'Sinead', 'Apple',
                'Diane', 'Juanita', 'Mckenna', 'Siobhan', 'April', 'Dianna', 'Jude', 'Mckenzie', 'Sky', 'Aqua',
                'Dianne', 'Judith', 'Mea', 'Skye', 'Arabella', 'Dido', 'Judy', 'Meadow', 'Skylar', 'Arabelle', 'Dina',
                'Jules', 'Meagan', 'Skyler', 'Aria', 'Dionne', 'Julia', 'Meera', 'Sloane', 'Ariadne', 'Dior', 'Juliana',
                'Meg', 'Snow', 'Ariana', 'Dixie', 'Julianna', 'Megan', 'Sofia', 'Arianna', 'Dolly', 'Julianne',
                'Meghan', 'Sofie', 'Arianne', 'Dolores', 'Julie', 'Mei', 'Sondra', 'Ariel', 'Dominique', 'Julienne',
                'Mel', 'Sonia', 'Ariella', 'Donna', 'Juliet', 'Melanie', 'Sonja', 'Arielle', 'Dora', 'Juliette',
                'Melina', 'Sonya', 'Arisha', 'Doreen', 'Julissa', 'Melinda', 'Sophia', 'Arleen', 'Doris', 'July',
                'Melissa', 'Sophie', 'Arlene', 'Dorothy', 'June', 'Melody', 'Sophy', 'Arlette', 'Dot', 'Juniper',
                'Mercedes', 'Sorrel', 'Artemis', 'Drew', 'Juno', 'Mercy', 'Spring', 'Arwen', 'Dulce', 'Justice',
                'Meredith', 'Stacey', 'Arya', 'Dusty', 'Justina', 'Merida', 'Staci', 'Asha', 'Eabha', 'Justine',
                'Meryl', 'Stacie', 'Ashanti', 'Ebony', 'Kacey', 'Mia', 'Stacy', 'Ashlee', 'Echo', 'Kadence', 'Michaela',
                'Star', 'Ashleigh', 'Eden', 'Kaelyn', 'Michele', 'Starla', 'Ashley', 'Edie', 'Kaidence', 'Michelle',
                'Stefanie', 'Ashlie', 'Edith', 'Kailey', 'Mika', 'Stella', 'Ashlyn', 'Edna', 'Kailyn', 'Mikaela',
                'Steph', 'Ashlynn', 'Edwina', 'Kaitlin', 'Mikayla', 'Stephanie', 'Ashton', 'Effie', 'Kaitlyn',
                'Mikhaela', 'Sue', 'Ashvini', 'Eileen', 'Kaitlynn', 'Mila', 'Sugar', 'Asia', 'Eilidh', 'Kalea',
                'Mildred', 'Suki', 'Asma', 'Eimear', 'Kaleigh', 'Milena', 'Summer', 'Aspen', 'Elaina', 'Kali', 'Miley',
                'Susan', 'Astrid', 'Elaine', 'Kalia', 'Millicent', 'Susanna', 'Athena', 'Elana', 'Kalista', 'Millie',
                'Susannah', 'Athene', 'Eleanor', 'Kaliyah', 'Milly', 'Susanne', 'Atlanta', 'Electra', 'Kallie', 'Mimi',
                'Susie', 'Aubreanna', 'Elektra', 'Kamala', 'Mina', 'Sutton', 'Aubree', 'Elen', 'Kamryn', 'Mindy',
                'Suzanna', 'Aubrey', 'Elena', 'Kara', 'Minerva', 'Suzanne', 'Audra', 'Eliana', 'Karen', 'Minnie',
                'Suzette', 'Audrey', 'Elin', 'Kari', 'Mira', 'Suzie', 'Audrina', 'Elina', 'Karin', 'Mirabel', 'Suzy',
                'Augustina', 'Elinor', 'Karina', 'Mirabelle', 'Sybil', 'Aurelia', 'Elisa', 'Karissa', 'Miracle',
                'Sydney', 'Aurora', 'Elisabeth', 'Karla', 'Miranda', 'Sylvia', 'Autumn', 'Elise', 'Karlee', 'Miriam',
                'Sylvie', 'Ava', 'Eliza', 'Karly', 'Mirielle', 'Tabatha', 'Avalon', 'Elizabeth', 'Karolina', 'Missie',
                'Tabitha', 'Avery', 'Ella', 'Karyn', 'Misty', 'Tagan', 'Avril', 'Elle', 'Kasey', 'Mitzi', 'Tahlia',
                'Aya', 'Ellen', 'Kassandra', 'Moira', 'Tala', 'Ayana', 'Ellery', 'Kassidy', 'Mollie', 'Talia', 'Ayanna',
                'Ellie', 'Kassie', 'Molly', 'Talitha', 'Ayesha', 'Ellis', 'Kat', 'Mona', 'Taliyah', 'Ayisha', 'Elly',
                'Katara', 'Monica', 'Tallulah', 'Ayla', 'Elodie', 'Katarina', 'Monika', 'Tamara', 'Azalea', 'Eloise',
                'Kate', 'Monique', 'Tamera', 'Azaria', 'Elora', 'Katelyn', 'Montana', 'Tami', 'Azariah', 'Elsa',
                'Katelynn', 'Montserrat', 'Tamia', 'Bailey', 'Elsie', 'Katerina', 'Morgan', 'Tamika', 'Barbara',
                'Elspeth', 'Katharine', 'Morgana', 'Tammi', 'Barbie', 'Elva', 'Katherine', 'Moya', 'Tammie', 'Bay',
                'Elvira', 'Kathleen', 'Muriel', 'Tammy', 'Baylee', 'Elysia', 'Kathryn', 'Mya', 'Tamra', 'Bea', 'Elyza',
                'Kathy', 'Myfanwy', 'Tamsin', 'Beatrice', 'Emanuela', 'Katia', 'Myla', 'Tania', 'Beatrix', 'Ember',
                'Katie', 'Myra', 'Tanika', 'Becca', 'Emelda', 'Katlyn', 'Myrna', 'Tanisha', 'Beccy', 'Emely', 'Katniss',
                'Myrtle', 'Tanya', 'Becky', 'Emer', 'Katrina', 'Nadene', 'Tara', 'Belinda', 'Emerald', 'Katy', 'Nadia',
                'Taryn', 'Bella', 'Emerson', 'Katya', 'Nadine', 'Tasha', 'Bellatrix', 'Emilee', 'Kay', 'Naja', 'Tasmin',
                'Belle', 'Emilia', 'Kaya', 'Nala', 'Tatiana', 'Benita', 'Emilie', 'Kaye', 'Nana', 'Tatum', 'Bernadette',
                'Emily', 'Kayla', 'Nancy', 'Tawana', 'Bernice', 'Emma', 'Kaylee', 'Nanette', 'Taya', 'Bertha',
                'Emmalee', 'Kayleigh', 'Naomi', 'Tayah', 'Beryl', 'Emmaline', 'Kayley', 'Natalia', 'Tayla', 'Bess',
                'Emmalyn', 'Kaylie', 'Natalie', 'Taylah', 'Beth', 'Emmanuelle', 'Kaylin', 'Natasha', 'Tayler', 'Bethan',
                'Emmeline', 'Keara', 'Naya', 'Taylor', 'Bethanie', 'Emmie', 'Keeley', 'Nayeli', 'Teagan', 'Bethany',
                'Emmy', 'Keely', 'Nell', 'Teegan', 'Betsy', 'Enid', 'Keira', 'Nellie', 'Tegan', 'Bettina', 'Enya',
                'Keisha', 'Nelly', 'Teigan', 'Betty', 'Erica', 'Kelis', 'Nena', 'Tenille', 'Beverly', 'Erika', 'Kelley',
                'Nerissa', 'Teresa', 'Beyonce', 'Erin', 'Kelli', 'Nessa', 'Teri', 'Bianca', 'Eris', 'Kellie', 'Nevaeh',
                'Terri', 'Billie', 'Ernestine', 'Kelly', 'Neve', 'Terrie', 'Blair', 'Eryn', 'Kelsey', 'Nia', 'Terry',
                'Blaire', 'Esmay', 'Kelsie', 'Niamh', 'Tess', 'Blake', 'Esme', 'Kendall', 'Nichola', 'Tessa', 'Blakely',
                'Esmeralda', 'Kendra', 'Nichole', 'Thalia', 'Blanche', 'Esparanza', 'Kenna', 'Nicki', 'Thea', 'Blaze',
                'Esperanza', 'Kennedy', 'Nicky', 'Thelma', 'Blessing', 'Estee', 'Kenzie', 'Nicola', 'Theodora', 'Bliss',
                'Estelle', 'Kera', 'Nicole', 'Theresa', 'Bloom', 'Ester', 'Keri', 'Nicolette', 'Therese', 'Blossom',
                'Esther', 'Kerian', 'Nieve', 'Thomasina', 'Blythe', 'Estrella', 'Kerri', 'Niki', 'Tia', 'Bobbi',
                'Ethel', 'Kerry', 'Nikita', 'Tiana', 'Bobbie', 'Eugenie', 'Kia', 'Nikki', 'Tiegan', 'Bobby', 'Eunice',
                'Kiana', 'Nila', 'Tiffany', 'Bonita', 'Eva', 'Kiara', 'Nina', 'Tilly', 'Bonnie', 'Evangelina', 'Kiera',
                'Nishka', 'Tina', 'Bonquesha', 'Evangeline', 'Kierra', 'Noelle', 'Tisha', 'Braelyn', 'Eve', 'Kiersten',
                'Noemi', 'Toni', 'Brandi', 'Evelin', 'Kiki', 'Nola', 'Tonia', 'Brandy', 'Evelyn', 'Kiley', 'Nora',
                'Tonya', 'Braylee', 'Everly', 'Kim', 'Norah', 'Tori', 'Brea', 'Evie', 'Kimberlee', 'Noreen', 'Tracey',
                'Breanna', 'Evita', 'Kimberley', 'Norma', 'Traci', 'Bree', 'Fabrizia', 'Kimberly', 'Nova', 'Tracie',
                'Breeze', 'Faith', 'Kimbriella', 'Nyla', 'Tracy', 'Brenda', 'Fallon', 'Kimmy', 'Oasis', 'Tricia',
                'Brenna', 'Fanny', 'Kinley', 'Ocean', 'Trina', 'Bria', 'Farah', 'Kinsey', 'Octavia', 'Trinity',
                'Briana', 'Farrah', 'Kinsley', 'Odalis', 'Trish', 'Brianna', 'Fatima', 'Kira', 'Odalys', 'Trisha',
                'Brianne', 'Fawn', 'Kirsten', 'Odele', 'Trista', 'Briar', 'Fay', 'Kirstin', 'Odelia', 'Trixie',
                'Bridget', 'Faye', 'Kirsty', 'Odette', 'Trixy', 'Bridgette', 'Felicia', 'Kitty', 'Olga', 'Trudy',
                'Bridie', 'Felicity', 'Kizzy', 'Olive', 'Tula', 'Briella', 'Fern', 'Kloe', 'Olivia', 'Tulip', 'Brielle',
                'Fernanda', 'Kora', 'Oona', 'Tyra', 'Brigid', 'Ffion', 'Kori', 'Oonagh', 'Ulrica', 'Briley', 'Fifi',
                'Kourtney', 'Opal', 'Uma', 'Brinley', 'Fiona', 'Kris', 'Ophelia', 'Una', 'Briony', 'Fleur', 'Krista',
                'Oprah', 'Ursula', 'Brisa', 'Flick', 'Kristen', 'Oriana', 'Valentina', 'Bristol', 'Flo', 'Kristi',
                'Orianna', 'Valeria', 'Britney', 'Flora', 'Kristie', 'Orla', 'Valerie', 'Britt', 'Florence', 'Kristin',
                'Orlaith', 'Valery', 'Brittany', 'Fran', 'Kristina', 'Page', 'Vanessa', 'Brittney', 'Frances',
                'Kristine', 'Paige', 'Veda', 'Brogan', 'Francesca', 'Kristy', 'Paisley', 'Velma', 'Bronagh', 'Francine',
                'Krystal', 'Paloma', 'Venetia', 'Bronte', 'Frankie', 'Kyla', 'Pam', 'Venus', 'Bronwen', 'Freda',
                'Kylee', 'Pamela', 'Vera', 'Bronwyn', 'Freya', 'Kyleigh', 'Pandora', 'Verity', 'Brook', 'Frida',
                'Kylie', 'Pansy', 'Veronica', 'Brooke', 'Gabby', 'Kyra', 'Paola', 'Vicki', 'Brooklyn', 'Gabriela',
                'Lacey', 'Paris', 'Vickie', 'Brooklynn', 'Gabriella', 'Lacie', 'Patience', 'Vicky', 'Bryanna',
                'Gabrielle', 'Lacy', 'Patrice', 'Victoria', 'Brylee', 'Gail', 'Ladonna', 'Patricia', 'Vienna', 'Bryn',
                'Garnet', 'Laila', 'Patsy', 'Viola', 'Brynlee', 'Gayle', 'Lainey', 'Patti', 'Violet', 'Brynn', 'Gaynor',
                'Lakyn', 'Patty', 'Violetta', 'Bryony', 'Geena', 'Lala', 'Paula', 'Virginia', 'Bunty', 'Gemma', 'Lana',
                'Paulette', 'Vivian', 'Cadence', 'Gena', 'Laney', 'Paulina', 'Viviana', 'Cailin', 'Genesis', 'Lara',
                'Pauline', 'Vivien', 'Caitlan', 'Genevieve', 'Larissa', 'Payton', 'Vivienne', 'Caitlin', 'Georgette',
                'Latoya', 'Peace', 'Wallis', 'Caitlyn', 'Georgia', 'Laura', 'Pearl', 'Wanda', 'Caleigh', 'Georgie',
                'Laurel', 'Peggy', 'Waverley', 'Cali', 'Georgina', 'Lauren', 'Penelope', 'Wendi', 'Calista',
                'Geraldine', 'Laurie', 'Penny', 'Wendy', 'Callie', 'Gert', 'Lauryn', 'Perla', 'Whitney', 'Calliope',
                'Gertrude', 'Lavana', 'Perrie', 'Wilhelmina', 'Callista', 'Gia', 'Lavender', 'Persephone', 'Willa',
                'Calypso', 'Gianna', 'Lavinia', 'Petra', 'Willow', 'Cambria', 'Gigi', 'Layla', 'Petunia', 'Wilma',
                'Cameron', 'Gillian', 'Lea', 'Peyton', 'Winnie', 'Cami', 'Gina', 'Leah', 'Phillipa', 'Winnifred',
                'Camila', 'Ginger', 'Leandra', 'Philomena', 'Winona', 'Camilla', 'Ginny', 'Leann', 'Phoebe', 'Winter',
                'Camille', 'Giovanna', 'Leanna', 'Phoenix', 'Xandra', 'Camryn', 'Gisela', 'Leanne', 'Phyllis', 'Xanthe',
                'Candace', 'Giselle', 'Lee', 'Piper', 'Xaviera', 'Candice', 'Gisselle', 'Leela', 'Pippa', 'Xena',
                'Candis', 'Gladys', 'Leena', 'Pixie', 'Xia', 'Candy', 'Glenda', 'Leia', 'Polly', 'Ximena', 'Caoimhe',
                'Glenys', 'Leigh', 'Pollyanna', 'Xochil', 'Caprice', 'Gloria', 'Leila', 'Poppy', 'Xochitl', 'Cara',
                'Glynis', 'Leilani', 'Portia', 'Yasmin', 'Carina', 'Golda', 'Lela', 'Precious', 'Yasmine', 'Caris',
                'Goldie', 'Lena', 'Presley', 'Yazmin', 'Carissa', 'Grace', 'Lenore', 'Preslie', 'Yelena', 'Carla',
                'Gracelyn', 'Leona', 'Primrose', 'Yesenia', 'Carlene', 'Gracie', 'Leonie', 'Princess', 'Yolanda',
                'Carley', 'Grainne', 'Leora', 'Priscilla', 'Ysabel', 'Carlie', 'Greta', 'Lesley', 'Priya', 'Yulissa',
                'Carly', 'Gretchen', 'Leslie', 'Promise', 'Yvaine', 'Carlynn', 'Griselda', 'Lesly', 'Prudence',
                'Yvette', 'Carmel', 'Guadalupe', 'Leticia', 'Prue', 'Yvonne', 'Carmela', 'Guinevere', 'Letitia',
                'Queenie', 'Zada', 'Carmen', 'Gwen', 'Lettie', 'Quiana', 'Zaheera', 'Carol', 'Gwendolyn', 'Lexi',
                'Quinn', 'Zahra', 'Carole', 'Gwyneth', 'Lexia', 'Rabia', 'Zaira', 'Carolina', 'Habiba', 'Lexie',
                'Rachael', 'Zakia', 'Caroline', 'Hadley', 'Lexis', 'Rachel', 'Zali', 'Carolyn', 'Hailee', 'Leyla',
                'Rachelle', 'Zara', 'Carrie', 'Hailey', 'Lia', 'Rae', 'Zaria', 'Carter', 'Haleigh', 'Liana', 'Raegan',
                'Zaya', 'Carys', 'Haley', 'Lianne', 'Raelyn', 'Zayla', 'Casey', 'Halle', 'Libbie', 'Raina', 'Zelda',
                'Cassandra', 'Hallie', 'Libby', 'Raine', 'Zelida', 'Cassia', 'Hanna', 'Liberty', 'Ramona', 'Zelina',
                'Cassidy', 'Hannah', 'Lidia', 'Ramsha', 'Zena', 'Cassie', 'Harley', 'Liesl', 'Randi', 'Zendaya', 'Cat',
                'Harmony', 'Lila', 'Rani', 'Zia', 'Catalina', 'Harper', 'Lilac', 'Rania', 'Zina', 'Cate', 'Harriet',
                'Lilah', 'Raquel', 'Ziva', 'Caterina', 'Hattie', 'Lili', 'Raven', 'Zoe', 'Cathalina', 'Haven', 'Lilian',
                'Raya', 'Zoey', 'Catherine', 'Hayden', 'Liliana', 'Rayna', 'Zola', 'Cathleen', 'Haylee', 'Lilita',
                'Rayne', 'Zora', 'Cathy', 'Hayley', 'Lilith', 'Reagan', 'Zoya', 'Catlin', 'Hazel', 'Lillia', 'Reanna',
                'Zula', 'Catrina', 'Hazeline', 'Lillian', 'Reanne', 'Zuri', 'Catriona', 'Heather', 'Lillie', 'Rebecca',
                'Zyana', 'Cayla', 'Heaven',
            ],
            'male'   => [
                'Aaron', 'Clay', 'Gino', 'Laurie', 'Richard', 'Abdul', 'Clayton', 'Giorgio', 'Lawrence', 'Richie',
                'Abdullah', 'Clement', 'Giovanni', 'Lawson', 'Rick', 'Abe', 'Cliff', 'Glen', 'Layne', 'Rickey', 'Abel',
                'Clifford', 'Glenn', 'Layton', 'Rickie', 'Abraham', 'Clifton', 'Glyndwr', 'Leaf', 'Ricky', 'Abram',
                'Clint', 'Godfrey', 'Leandro', 'Rico', 'Abriel', 'Clinton', 'Godric', 'Lebron', 'Rider', 'Ace', 'Clive',
                'Godwin', 'Lee', 'Rik', 'Adam', 'Clyde', 'Gonzalo', 'Leigh', 'Riker', 'Adan', 'Coby', 'Gordon',
                'Leighton', 'Riley', 'Addison', 'Cody', 'Grady', 'Leland', 'Rio', 'Ade', 'Cohen', 'Graeme', 'Lennie',
                'River', 'Aden', 'Colby', 'Graham', 'Lennon', 'Roan', 'Adnan', 'Cole', 'Grant', 'Lennox', 'Rob',
                'Adonis', 'Colin', 'Grayson', 'Lenny', 'Robbie', 'Adrian', 'Collin', 'Greg', 'Leo', 'Robby', 'Adriel',
                'Colm', 'Gregg', 'Leon', 'Robert', 'Ahmad', 'Colt', 'Gregor', 'Leonard', 'Roberto', 'Ahmed', 'Colton',
                'Gregory', 'Leonardo', 'Robin', 'Aidan', 'Conan', 'Grey', 'Leonel', 'Rocco', 'Aiden', 'Conner',
                'Greyson', 'Leopold', 'Rock', 'Ainsley', 'Connor', 'Griffin', 'Leroy', 'Rocky', 'Ajay', 'Conor',
                'Guillermo', 'Les', 'Rod', 'Al', 'Conrad', 'Gunnar', 'Leslie', 'Roderick', 'Alain', 'Constantine',
                'Gunner', 'Lester', 'Rodger', 'Alan', 'Cooper', 'Gus', 'Leuan', 'Rodney', 'Alastair', 'Corbin',
                'Gustav', 'Lev', 'Rodolfo', 'Albert', 'Corey', 'Gustavo', 'Leven', 'Rodrigo', 'Alberto', 'Cormac',
                'Guy', 'Levi', 'Rogelio', 'Albie', 'Cornelius', 'Haden', 'Lewis', 'Roger', 'Alden', 'Cory', 'Haiden',
                'Lex', 'Rohan', 'Aldo', 'Craig', 'Hal', 'Liam', 'Roland', 'Aldric', 'Cristian', 'Hamish', 'Lief',
                'Rolando', 'Alec', 'Cristobal', 'Han', 'Lincoln', 'Roman', 'Alejandro', 'Crosby', 'Hank', 'Link',
                'Romeo', 'Alen', 'Cruz', 'Hans', 'Linus', 'Ron', 'Alesandro', 'Cullen', 'Harlan', 'Lionel', 'Ronald',
                'Alex', 'Curt', 'Harley', 'Lisandro', 'Ronan', 'Alexander', 'Curtis', 'Harold', 'Lloyd', 'Ronnie',
                'Alexis', 'Cuthbert', 'Harris', 'Lochlan', 'Ronny', 'Alfie', 'Cyril', 'Harrison', 'Logan', 'Roosevelt',
                'Alfonso', 'Cyrus', 'Harry', 'Loki', 'Rory', 'Alfred', 'Dacey', 'Harvey', 'London', 'Roscoe', 'Alfredo',
                'Daire', 'Hassan', 'Lonnie', 'Ross', 'Ali', 'Dakota', 'Hayden', 'Lorcan', 'Rowan', 'Alistair', 'Dale',
                'Hayes', 'Loren', 'Roy', 'Allan', 'Dallas', 'Heath', 'Lorenzo', 'Royce', 'Allen', 'Dalton', 'Hector',
                'Loris', 'Ruairi', 'Alonzo', 'Damian', 'Hendrik', 'Lou', 'Ruben', 'Aloysius', 'Damien', 'Hendrix',
                'Louie', 'Rubin', 'Alphonso', 'Damion', 'Henley', 'Louis', 'Rudolph', 'Alton', 'Damon', 'Henri',
                'Lowell', 'Rudy', 'Alvin', 'Dan', 'Henry', 'Luca', 'Rufus', 'Amari', 'Dana', 'Herbert', 'Lucas',
                'Rupert', 'Amir', 'Dane', 'Herman', 'Lucian', 'Russ', 'Amit', 'Daniel', 'Heston', 'Luciano', 'Russell',
                'Amos', 'Danny', 'Hilary', 'Luigi', 'Rusty', 'Anand', 'Dante', 'Holden', 'Luis', 'Ryan', 'Anderson',
                'Dara', 'Homer', 'Lukas', 'Ryder', 'Andre', 'Daragh', 'Horace', 'Luke', 'Ryker', 'Andreas', 'Darcy',
                'Horatio', 'Luther', 'Rylan', 'Andres', 'Daren', 'Howard', 'Lyle', 'Ryland', 'Andrew', 'Darian',
                'Hubert', 'Lyndon', 'Ryley', 'Andy', 'Darin', 'Hudson', 'Lynn', 'Sacha', 'Angel', 'Dario', 'Hugh',
                'Lysander', 'Said', 'Angelo', 'Darius', 'Hugo', 'Mack', 'Salvador', 'Angus', 'Darnell', 'Humberto',
                'Maddox', 'Salvatore', 'Ansel', 'Darragh', 'Humphrey', 'Magnus', 'Sam', 'Anson', 'Darrel', 'Hunter',
                'Maison', 'Samir', 'Anthony', 'Darrell', 'Huw', 'Malachi', 'Sammy', 'Anton', 'Darren', 'Hywel',
                'Malakai', 'Samson', 'Antonio', 'Darrin', 'Iain', 'Malcolm', 'Samuel', 'Antony', 'Darryl', 'Ian',
                'Malik', 'Sandeep', 'Apollo', 'Darryn', 'Ianto', 'Malloy', 'Sandy', 'Aran', 'Darwin', 'Ibrahim',
                'Manny', 'Sanjay', 'Archer', 'Daryl', 'Idris', 'Manuel', 'Santiago', 'Archie', 'Dash', 'Ieuan', 'Marc',
                'Sasha', 'Ari', 'Dashawn', 'Iggy', 'Marcel', 'Saul', 'Arjun', 'Dave', 'Ignacio', 'Marco', 'Sawyer',
                'Arlo', 'David', 'Igor', 'Marcos', 'Scot', 'Arman', 'Davin', 'Ike', 'Marcus', 'Scott', 'Armando',
                'Davion', 'Imran', 'Marik', 'Scottie', 'Arnold', 'Davis', 'Indiana', 'Mario', 'Scotty', 'Aron',
                'Dawson', 'Inigo', 'Marion', 'Seamus', 'Arran', 'Dax', 'Ira', 'Mark', 'Sean', 'Arrie', 'Daxter',
                'Irvin', 'Marley', 'Seb', 'Art', 'Daxton', 'Irving', 'Marlon', 'Sebastian', 'Arthur', 'Dayton', 'Irwin',
                'Marquis', 'Sebastien', 'Arturo', 'Deacon', 'Isaac', 'Marshall', 'Sebestian', 'Arun', 'Dean', 'Isaiah',
                'Martin', 'Sergio', 'Arwin', 'Deandre', 'Isiah', 'Marty', 'Seth', 'Asa', 'Declan', 'Isidore', 'Martyn',
                'Shadrach', 'Asad', 'Deepak', 'Ismael', 'Marvin', 'Shane', 'Ash', 'Delbert', 'Israel', 'Mason',
                'Shannon', 'Ashby', 'Demetrius', 'Issac', 'Massimo', 'Shaun', 'Asher', 'Denis', 'Ivan', 'Mat', 'Shawn',
                'Ashley', 'Dennis', 'Ivor', 'Mateo', 'Shay', 'Ashton', 'Denver', 'Jace', 'Mathew', 'Shayne', 'Ashwin',
                'Denzel', 'Jack', 'Matt', 'Shea', 'Aspen', 'Deon', 'Jackie', 'Matthew', 'Sheldon', 'Aston', 'Derek',
                'Jackson', 'Matthias', 'Shelton', 'Athan', 'Dermot', 'Jacob', 'Maurice', 'Sherlock', 'Atticus',
                'Derrick', 'Jacoby', 'Mauricio', 'Sherman', 'Aubrey', 'Deshaun', 'Jacques', 'Maverick', 'Shiloh',
                'Audwin', 'Deshawn', 'Jaden', 'Max', 'Sid', 'August', 'Desmond', 'Jadon', 'Maxim', 'Sidney', 'Augustus',
                'Dev', 'Jagger', 'Maximilian', 'Silas', 'Austen', 'Devin', 'Jago', 'Maximus', 'Simeon', 'Austin',
                'Devlin', 'Jai', 'Maxwell', 'Simon', 'Avery', 'Devon', 'Jaiden', 'Mehdi', 'Sky', 'Axel', 'Dewayne',
                'Jaime', 'Mehtab', 'Skylar', 'Ayaan', 'Dewey', 'Jak', 'Mekhi', 'Skyler', 'Ayden', 'Dexter', 'Jake',
                'Mel', 'Slade', 'Bailey', 'Diarmuid', 'Jakob', 'Melvin', 'Sol', 'Barack', 'Dick', 'Jalen', 'Merick',
                'Solomon', 'Barclay', 'Dicky', 'Jamal', 'Mervyn', 'Sonny', 'Barnaby', 'Diego', 'James', 'Micah',
                'Soren', 'Barney', 'Dilan', 'Jameson', 'Michael', 'Spencer', 'Barrett', 'Dillon', 'Jamie', 'Micheal',
                'Spike', 'Barron', 'Dimitri', 'Jamison', 'Mick', 'Stacey', 'Barry', 'Dinesh', 'Jan', 'Mickey', 'Stacy',
                'Bart', 'Dino', 'Jared', 'Miguel', 'Stan', 'Bartholomew', 'Dion', 'Jarod', 'Mike', 'Stanley', 'Basil',
                'Dirk', 'Jarrett', 'Mikey', 'Stefan', 'Bastian', 'Django', 'Jarrod', 'Milan', 'Stephan', 'Baxter',
                'Dmitri', 'Jarvis', 'Miles', 'Stephen', 'Bay', 'Dominic', 'Jase', 'Miller', 'Sterling', 'Baylor',
                'Dominick', 'Jason', 'Milo', 'Steve', 'Bear', 'Don', 'Jasper', 'Milton', 'Steven', 'Beau', 'Donald',
                'Javier', 'Misha', 'Stevie', 'Beck', 'Donnie', 'Javon', 'Mitch', 'Stewart', 'Beckett', 'Donovan', 'Jax',
                'Mitchell', 'Stone', 'Bellamy', 'Dorian', 'Jaxon', 'Mitt', 'Storm', 'Ben', 'Doug', 'Jaxson', 'Moe',
                'Stuart', 'Benedict', 'Douglas', 'Jay', 'Mohamed', 'Sufyan', 'Benjamin', 'Doyle', 'Jayce', 'Mohammad',
                'Sullivan', 'Benji', 'Drake', 'Jayden', 'Mohammed', 'Sven', 'Benjy', 'Drew', 'Jaydon', 'Moises',
                'Sylvester', 'Bennett', 'Duane', 'Jaylen', 'Monte', 'Tadhg', 'Bennie', 'Duke', 'Jaylin', 'Monty',
                'Talon', 'Benny', 'Duncan', 'Jaylon', 'Mordecai', 'Tam', 'Benson', 'Dustin', 'Jayson', 'Morgan',
                'Tanner', 'Bentley', 'Dwayne', 'Jeb', 'Morris', 'Tariq', 'Bently', 'Dwight', 'Jebediah', 'Moses',
                'Tarquin', 'Bernard', 'Dylan', 'Jed', 'Muhammad', 'Tate', 'Bernardo', 'Eamon', 'Jediah', 'Murphy',
                'Taylor', 'Bernie', 'Earl', 'Jedidiah', 'Murray', 'Ted', 'Bert', 'Earnest', 'Jeff', 'Myles', 'Teddy',
                'Bertie', 'Eason', 'Jefferson', 'Myron', 'Teo', 'Bertram', 'Easton', 'Jeffery', 'Nash', 'Terence',
                'Bev', 'Ed', 'Jeffrey', 'Nasir', 'Terrance', 'Bevan', 'Eddie', 'Jeffry', 'Nate', 'Terrell', 'Bill',
                'Eddy', 'Jensen', 'Nath', 'Terrence', 'Billy', 'Eden', 'Jenson', 'Nathan', 'Terry', 'Bjorn', 'Edgar',
                'Jerald', 'Nathanael', 'Tevin', 'Bladen', 'Edison', 'Jeremiah', 'Nathaniel', 'Tex', 'Blain', 'Edmund',
                'Jeremy', 'Neal', 'Thad', 'Blaine', 'Edouard', 'Jericho', 'Ned', 'Thaddeus', 'Blair', 'Edric',
                'Jermaine', 'Nehemiah', 'Theo', 'Blaise', 'Edsel', 'Jerome', 'Neil', 'Theodore', 'Blake', 'Eduardo',
                'Jerry', 'Nelson', 'Theophilus', 'Blaze', 'Edward', 'Jesse', 'Nesbit', 'Thomas', 'Blue', 'Edwardo',
                'Jessie', 'Nestor', 'Thor', 'Bob', 'Edwin', 'Jesus', 'Neville', 'Tiago', 'Bobby', 'Efrain', 'Jet',
                'Nevin', 'Tiberius', 'Bodie', 'Efren', 'Jethro', 'Niall', 'Tiger', 'Boris', 'Egan', 'Jett', 'Nicholas',
                'Tim', 'Boston', 'Egon', 'Jim', 'Nick', 'Timmy', 'Bowen', 'Eli', 'Jimmie', 'Nickolas', 'Timothy',
                'Boyd', 'Elias', 'Jimmy', 'Nicky', 'Tito', 'Brad', 'Elijah', 'Joachim', 'Nico', 'Titus', 'Braden',
                'Eliot', 'Joaquin', 'Nicolas', 'Tobias', 'Bradford', 'Elisha', 'Jody', 'Nigel', 'Tobin', 'Bradley',
                'Ellington', 'Joe', 'Niklaus', 'Toby', 'Bradwin', 'Elliot', 'Joel', 'Nikolai', 'Tod', 'Brady',
                'Elliott', 'Joey', 'Nikolas', 'Todd', 'Braeden', 'Ellis', 'Johan', 'Nile', 'Tom', 'Bram', 'Elmer',
                'John', 'Nils', 'Tomas', 'Branden', 'Elmo', 'Johnathan', 'Noah', 'Tommie', 'Brandon', 'Elton',
                'Johnathon', 'Noe', 'Tommy', 'Brantley', 'Elvis', 'Johnnie', 'Noel', 'Tony', 'Braxton', 'Elwyn',
                'Johnny', 'Nolan', 'Torin', 'Brayan', 'Emanuel', 'Jon', 'Norbert', 'Toryn', 'Brayden', 'Emerson',
                'Jonah', 'Norman', 'Trace', 'Braydon', 'Emery', 'Jonas', 'Oakes', 'Tracey', 'Braylon', 'Emet',
                'Jonathan', 'Oakley', 'Tracy', 'Brendan', 'Emil', 'Jonathon', 'Octavio', 'Travis', 'Brenden',
                'Emiliano', 'Jonty', 'Oisin', 'Tray', 'Brendon', 'Emilio', 'Jordan', 'Olaf', 'Tremaine', 'Brennan',
                'Emmanuel', 'Jordon', 'Oli', 'Trent', 'Brent', 'Emmerson', 'Jordy', 'Oliver', 'Trenton', 'Brentley',
                'Emmet', 'Jorge', 'Ollie', 'Trevon', 'Brenton', 'Emmett', 'Jose', 'Olly', 'Trevor', 'Bret', 'Ennio',
                'Joseph', 'Omar', 'Trey', 'Brett', 'Enoch', 'Josh', 'Oran', 'Tristan', 'Brevin', 'Enrique', 'Joshua',
                'Orion', 'Tristen', 'Brevyn', 'Enzo', 'Josiah', 'Orlando', 'Triston', 'Brian', 'Eoghan', 'Josue',
                'Orson', 'Troy', 'Brice', 'Eoin', 'Jovan', 'Oscar', 'Truman', 'Bridie', 'Eric', 'Juan', 'Osvaldo',
                'Tucker', 'Brighton', 'Erick', 'Judah', 'Oswald', 'Ty', 'Brinley', 'Erik', 'Judas', 'Otis', 'Tyler',
                'Brock', 'Ernest', 'Judd', 'Otto', 'Tyrese', 'Brodie', 'Ernesto', 'Jude', 'Owen', 'Tyrone', 'Brody',
                'Ernie', 'Julian', 'Ozzie', 'Tyson', 'Brogan', 'Errol', 'Julio', 'Ozzy', 'Ulysses', 'Bronson', 'Ervin',
                'Julius', 'Pablo', 'Umar', 'Brooks', 'Erwin', 'Justice', 'Paco', 'Uriah', 'Bruce', 'Esteban', 'Justin',
                'Paddy', 'Uriel', 'Bruno', 'Ethan', 'Kade', 'Padraig', 'Usama', 'Bryan', 'Ethen', 'Kaden', 'Palmer',
                'Valentin', 'Bryant', 'Etienne', 'Kai', 'Paolo', 'Valentine', 'Bryce', 'Euan', 'Kaiden', 'Parker',
                'Valentino', 'Bryden', 'Euen', 'Kaine', 'Pascal', 'Van', 'Brydon', 'Eugene', 'Kale', 'Pat', 'Vance',
                'Bryon', 'Eustace', 'Kaleb', 'Patrick', 'Vasco', 'Bryson', 'Evan', 'Kameron', 'Paul', 'Vaughn', 'Buck',
                'Evangelos', 'Kane', 'Paxton', 'Vernon', 'Buddy', 'Evelyn', 'Karl', 'Payton', 'Victor', 'Burt',
                'Everett', 'Karson', 'Pearce', 'Vidal', 'Burton', 'Ewan', 'Kash', 'Pedro', 'Vihan', 'Buster', 'Ezekiel',
                'Kasper', 'Percy', 'Vijay', 'Butch', 'Ezio', 'Kayden', 'Perry', 'Vikram', 'Byron', 'Ezra', 'Kaylen',
                'Petar', 'Vince', 'Cadby', 'Fabian', 'Kayson', 'Pete', 'Vincent', 'Cade', 'Fabio', 'Keanu', 'Peter',
                'Vinnie', 'Caden', 'Faisal', 'Keaton', 'Peyton', 'Virgil', 'Cael', 'Farley', 'Kedrick', 'Phebian',
                'Vishal', 'Caelan', 'Febian', 'Keegan', 'Phil', 'Vivian', 'Caesar', 'Felipe', 'Keenan', 'Philip',
                'Vlad', 'Cai', 'Felix', 'Keith', 'Philippe', 'Vladimir', 'Caiden', 'Fergus', 'Kellan', 'Phillip',
                'Wade', 'Cain', 'Fernand', 'Kellen', 'Phineas', 'Walker', 'Caius', 'Fernando', 'Kellin', 'Phoenix',
                'Wallace', 'Cal', 'Fidel', 'Kelly', 'Pierce', 'Walter', 'Cale', 'Finbar', 'Kelvin', 'Piers', 'Warren',
                'Caleb', 'Finlay', 'Ken', 'Pip', 'Waylon', 'Calhoun', 'Finley', 'Kendall', 'Porter', 'Wayne', 'Callan',
                'Finn', 'Kendrick', 'Poul', 'Wendell', 'Callen', 'Finnian', 'Kennedy', 'Prakash', 'Wes', 'Callum',
                'Finnigan', 'Kenneth', 'Preston', 'Wesley', 'Calum', 'Fionn', 'Kenny', 'Prince', 'Weston', 'Calvin',
                'Fletcher', 'Kent', 'Princeton', 'Wilbert', 'Cam', 'Floyd', 'Kenton', 'Quentin', 'Wilbur', 'Camden',
                'Flynn', 'Kerry', 'Quincy', 'Wiley', 'Cameron', 'Ford', 'Kevin', 'Quinlan', 'Wilfred', 'Campbell',
                'Forest', 'Khalid', 'Quinn', 'Wilhelm', 'Camron', 'Forrest', 'Khalil', 'Quinton', 'Will', 'Carey',
                'Foster', 'Kian', 'Quintrell', 'Willam', 'Carl', 'Fox', 'Kiefer', 'Rafael', 'Willard', 'Carlisle',
                'Francesco', 'Kieran', 'Rafferty', 'Willem', 'Carlos', 'Francis', 'Kieron', 'Raheem', 'William',
                'Carlton', 'Francisco', 'Killian', 'Rahul', 'Willie', 'Carsen', 'Frank', 'Kim', 'Raiden', 'Willis',
                'Carson', 'Frankie', 'Kingsley', 'Raj', 'Wilson', 'Carter', 'Franklin', 'Kingston', 'Rajesh', 'Winston',
                'Cary', 'Franklyn', 'Kip', 'Ralph', 'Wolfgang', 'Casey', 'Fraser', 'Kiran', 'Ram', 'Woody', 'Cash',
                'Fred', 'Kirby', 'Rameel', 'Wyatt', 'Cason', 'Freddie', 'Kirk', 'Ramon', 'Xander', 'Casper', 'Freddy',
                'Kit', 'Ramsey', 'Xavier', 'Cassius', 'Frederick', 'Klaus', 'Randal', 'Xerxes', 'Castiel', 'Fredrick',
                'Klay', 'Randall', 'Yahir', 'Castor', 'Fritz', 'Knox', 'Randolph', 'Yardley', 'Cathal', 'Gabe', 'Kobe',
                'Randy', 'Yehudi', 'Cato', 'Gabriel', 'Koby', 'Raoul', 'Yestin', 'Cavan', 'Gael', 'Kody', 'Raphael',
                'York', 'Cayden', 'Gaelan', 'Kolby', 'Rashad', 'Yuri', 'Caydon', 'Gage', 'Kris', 'Rashan', 'Yusuf',
                'Cecil', 'Gale', 'Krish', 'Rashid', 'Yves', 'Cedric', 'Galen', 'Kristian', 'Raul', 'Zac', 'Cesar',
                'Gannon', 'Kristoff', 'Ravi', 'Zach', 'Chad', 'Gareth', 'Kristopher', 'Ray', 'Zachariah', 'Chance',
                'Garman', 'Kurt', 'Raylan', 'Zachary', 'Chandler', 'Garrett', 'Kurtis', 'Raymond', 'Zachery',
                'Channing', 'Garrison', 'Kye', 'Reece', 'Zack', 'Charles', 'Garry', 'Kylar', 'Reed', 'Zackary',
                'Charley', 'Garth', 'Kyle', 'Reef', 'Zackery', 'Charlie', 'Gary', 'Kylen', 'Reese', 'Zaiden',
                'Charlton', 'Gaston', 'Kyler', 'Reggie', 'Zain', 'Chase', 'Gavin', 'Kyran', 'Reginald', 'Zaine', 'Chaz',
                'Gene', 'Kyrin', 'Rehan', 'Zak', 'Che', 'Geoff', 'Kyron', 'Reid', 'Zander', 'Chesney', 'Geoffrey',
                'Lacey', 'Reilly', 'Zane', 'Chester', 'George', 'Lachlan', 'Remco', 'Zayden', 'Chevy', 'Geraint',
                'Lake', 'Remington', 'Zayn', 'Chip', 'Gerald', 'Lamar', 'Remy', 'Zayne', 'Chris', 'Gerard', 'Lamont',
                'Ren', 'Zeb', 'Christian', 'Gerardo', 'Lance', 'Rene', 'Zebulon', 'Christopher', 'Germain', 'Landen',
                'Reuben', 'Zed', 'Chuck', 'Gerry', 'Landon', 'Rex', 'Zeke', 'Cian', 'Gian', 'Landyn', 'Reynaldo',
                'Zeph', 'Ciaran', 'Gibson', 'Lane', 'Reza', 'Ziggy', 'Cillian', 'Gideon', 'Langdon', 'Rhett', 'Zion',
                'Clancy', 'Gil', 'Langston', 'Rhys', 'Zoltan', 'Clarence', 'Gilbert', 'Larry', 'Rian', 'Zuriel',
                'Clark', 'Gilberto', 'Lars', 'Ricardo', 'Zylen', 'Claude', 'Giles', 'Laurence', 'Rich',
            ],
            'family' => [
                'Smith', 'Johnson', 'Williams', 'Brown', 'Jones', 'Miller', 'Davis', 'Garcia', 'Rodriguez', 'Wilson',
                'Martinez', 'Anderson', 'Taylor', 'Thomas', 'Hernandez', 'Moore', 'Martin', 'Jackson', 'Thompson',
                'White', 'Lopez', 'Lee', 'Gonzalez', 'Harris', 'Clark', 'Lewis', 'Robinson', 'Walker', 'Perez', 'Hall',
                'Young', 'Allen', 'Sanchez', 'Wright', 'King', 'Scott', 'Green', 'Baker', 'Adams', 'Nelson', 'Hill',
                'Ramirez', 'Campbell', 'Mitchell', 'Roberts', 'Carter', 'Phillips', 'Evans', 'Turner', 'Torres',
                'Parker', 'Collins', 'Edwards', 'Stewart', 'Flores', 'Morris', 'Nguyen', 'Murphy', 'Rivera', 'Cook',
                'Rogers', 'Morgan', 'Peterson', 'Cooper', 'Reed', 'Bailey', 'Bell', 'Gomez', 'Kelly', 'Howard', 'Ward',
                'Cox', 'Diaz', 'Richardson', 'Wood', 'Watson', 'Brooks', 'Bennett', 'Gray', 'James', 'Reyes', 'Cruz',
                'Hughes', 'Price', 'Myers', 'Long', 'Foster', 'Sanders', 'Ross', 'Morales', 'Powell', 'Sullivan',
                'Russell', 'Ortiz', 'Jenkins', 'Gutierrez', 'Perry', 'Butler', 'Barnes', 'Fisher', 'Henderson',
                'Coleman', 'Simmons', 'Patterson', 'Jordan', 'Reynolds', 'Hamilton', 'Graham', 'Kim', 'Gonzales',
                'Alexander', 'Ramos', 'Wallace', 'Griffin', 'West', 'Cole', 'Hayes', 'Chavez', 'Gibson', 'Bryant',
                'Ellis', 'Stevens', 'Murray', 'Ford', 'Marshall', 'Owens', 'Mcdonald', 'Harrison', 'Ruiz', 'Kennedy',
                'Wells', 'Alvarez', 'Woods', 'Mendoza', 'Castillo', 'Olson', 'Webb', 'Washington', 'Tucker', 'Freeman',
                'Burns', 'Henry', 'Vasquez', 'Snyder', 'Simpson', 'Crawford', 'Jimenez', 'Porter', 'Mason', 'Shaw',
                'Gordon', 'Wagner', 'Hunter', 'Romero', 'Hicks', 'Dixon', 'Hunt', 'Palmer', 'Robertson', 'Black',
                'Holmes', 'Stone', 'Meyer', 'Boyd', 'Mills', 'Warren', 'Fox', 'Rose', 'Rice', 'Moreno', 'Schmidt',
                'Patel', 'Ferguson', 'Nichols', 'Herrera', 'Medina', 'Ryan', 'Fernandez', 'Weaver', 'Daniels',
                'Stephens', 'Gardner', 'Payne', 'Kelley', 'Dunn', 'Pierce', 'Arnold', 'Tran', 'Spencer', 'Peters',
                'Hawkins', 'Grant', 'Hansen', 'Castro', 'Hoffman', 'Hart', 'Elliott', 'Cunningham', 'Knight', 'Bradley',
                'Carroll', 'Hudson', 'Duncan', 'Armstrong', 'Berry', 'Andrews', 'Johnston', 'Ray', 'Lane', 'Riley',
                'Carpenter', 'Perkins', 'Aguilar', 'Silva', 'Richards', 'Willis', 'Matthews', 'Chapman', 'Lawrence',
                'Garza', 'Vargas', 'Watkins', 'Wheeler', 'Larson', 'Carlson', 'Harper', 'George', 'Greene', 'Burke',
                'Guzman', 'Morrison', 'Munoz', 'Jacobs', 'Obrien', 'Lawson', 'Franklin', 'Lynch', 'Bishop', 'Carr',
                'Salazar', 'Austin', 'Mendez', 'Gilbert', 'Jensen', 'Williamson', 'Montgomery', 'Harvey', 'Oliver',
                'Howell', 'Dean', 'Hanson', 'Weber', 'Garrett', 'Sims', 'Burton', 'Fuller', 'Soto', 'Mccoy', 'Welch',
                'Chen', 'Schultz', 'Walters', 'Reid', 'Fields', 'Walsh', 'Little', 'Fowler', 'Bowman', 'Davidson',
                'May', 'Day', 'Schneider', 'Newman', 'Brewer', 'Lucas', 'Holland', 'Wong', 'Banks', 'Santos', 'Curtis',
                'Pearson', 'Delgado', 'Valdez', 'Pena', 'Rios', 'Douglas', 'Sandoval', 'Barrett', 'Hopkins', 'Keller',
                'Guerrero', 'Stanley', 'Bates', 'Alvarado', 'Beck', 'Ortega', 'Wade', 'Estrada', 'Contreras', 'Barnett',
                'Caldwell', 'Santiago', 'Lambert', 'Powers', 'Chambers', 'Nunez', 'Craig', 'Leonard', 'Lowe', 'Rhodes',
                'Byrd', 'Gregory', 'Shelton', 'Frazier', 'Becker', 'Maldonado', 'Fleming', 'Vega', 'Sutton', 'Cohen',
                'Jennings', 'Parks', 'Mcdaniel', 'Watts', 'Barker', 'Norris', 'Vaughn', 'Vazquez', 'Holt', 'Schwartz',
                'Steele', 'Benson', 'Neal', 'Dominguez', 'Horton', 'Terry', 'Wolfe', 'Hale', 'Lyons', 'Graves',
                'Haynes', 'Miles', 'Park', 'Warner', 'Padilla', 'Bush', 'Thornton', 'Mccarthy', 'Mann', 'Zimmerman',
                'Erickson', 'Fletcher', 'Mckinney', 'Page', 'Dawson', 'Joseph', 'Marquez', 'Reeves', 'Klein',
                'Espinoza', 'Baldwin', 'Moran', 'Love', 'Robbins', 'Higgins', 'Ball', 'Cortez', 'Le', 'Griffith',
                'Bowen', 'Sharp', 'Cummings', 'Ramsey', 'Hardy', 'Swanson', 'Barber', 'Acosta', 'Luna', 'Chandler',
                'Blair', 'Daniel', 'Cross', 'Simon', 'Dennis', 'Oconnor', 'Quinn', 'Gross', 'Navarro', 'Moss',
                'Fitzgerald', 'Doyle', 'Mclaughlin', 'Rojas', 'Rodgers', 'Stevenson', 'Singh', 'Yang', 'Figueroa',
                'Harmon', 'Newton', 'Paul', 'Manning', 'Garner', 'Mcgee', 'Reese', 'Francis', 'Burgess', 'Adkins',
                'Goodman', 'Curry', 'Brady', 'Christensen', 'Potter', 'Walton', 'Goodwin', 'Mullins', 'Molina',
                'Webster', 'Fischer', 'Campos', 'Avila', 'Sherman', 'Todd', 'Chang', 'Blake', 'Malone', 'Wolf',
                'Hodges', 'Juarez', 'Gill', 'Farmer', 'Hines', 'Gallagher', 'Duran', 'Hubbard', 'Cannon', 'Miranda',
                'Wang', 'Saunders', 'Tate', 'Mack', 'Hammond', 'Carrillo', 'Townsend', 'Wise', 'Ingram', 'Barton',
                'Mejia', 'Ayala', 'Schroeder', 'Hampton', 'Rowe', 'Parsons', 'Frank', 'Waters', 'Strickland', 'Osborne',
                'Maxwell', 'Chan', 'Deleon', 'Norman', 'Harrington', 'Casey', 'Patton', 'Logan', 'Bowers', 'Mueller',
                'Glover', 'Floyd', 'Hartman', 'Buchanan', 'Cobb', 'French', 'Kramer', 'Mccormick', 'Clarke', 'Tyler',
                'Gibbs', 'Moody', 'Conner', 'Sparks', 'Mcguire', 'Leon', 'Bauer', 'Norton', 'Pope', 'Flynn', 'Hogan',
                'Robles', 'Salinas', 'Yates', 'Lindsey', 'Lloyd', 'Marsh', 'Mcbride', 'Owen', 'Solis', 'Pham', 'Lang',
                'Pratt', 'Lara', 'Brock', 'Ballard', 'Trujillo', 'Shaffer', 'Drake', 'Roman', 'Aguirre', 'Morton',
                'Stokes', 'Lamb', 'Pacheco', 'Patrick', 'Cochran', 'Shepherd', 'Cain', 'Burnett', 'Hess', 'Li',
                'Cervantes', 'Olsen', 'Briggs', 'Ochoa', 'Cabrera', 'Velasquez', 'Montoya', 'Roth', 'Meyers',
                'Cardenas', 'Fuentes', 'Weiss', 'Hoover', 'Wilkins', 'Nicholson', 'Underwood', 'Short', 'Carson',
                'Morrow', 'Colon', 'Holloway', 'Summers', 'Bryan', 'Petersen', 'Mckenzie', 'Serrano', 'Wilcox', 'Carey',
                'Clayton', 'Poole', 'Calderon', 'Gallegos', 'Greer', 'Rivas', 'Guerra', 'Decker', 'Collier', 'Wall',
                'Whitaker', 'Bass', 'Flowers', 'Davenport', 'Conley', 'Houston', 'Huff', 'Copeland', 'Hood', 'Monroe',
                'Massey', 'Roberson', 'Combs', 'Franco', 'Larsen', 'Pittman', 'Randall', 'Skinner', 'Wilkinson',
                'Kirby', 'Cameron', 'Bridges', 'Anthony', 'Richard', 'Kirk', 'Bruce', 'Singleton', 'Mathis', 'Bradford',
                'Boone', 'Abbott', 'Charles', 'Allison', 'Sweeney', 'Atkinson', 'Horn', 'Jefferson', 'Rosales', 'York',
                'Christian', 'Phelps', 'Farrell', 'Castaneda', 'Nash', 'Dickerson', 'Bond', 'Wyatt', 'Foley', 'Chase',
                'Gates', 'Vincent', 'Mathews', 'Hodge', 'Garrison', 'Trevino', 'Villarreal', 'Heath', 'Dalton',
                'Valencia', 'Callahan', 'Hensley', 'Atkins', 'Huffman', 'Roy', 'Boyer', 'Shields', 'Lin', 'Hancock',
                'Grimes', 'Glenn', 'Cline', 'Delacruz', 'Camacho', 'Dillon', 'Parrish', 'Oneill', 'Melton', 'Booth',
                'Kane', 'Berg', 'Harrell', 'Pitts', 'Savage', 'Wiggins', 'Brennan', 'Salas', 'Marks', 'Russo', 'Sawyer',
                'Baxter', 'Golden', 'Hutchinson', 'Liu', 'Walter', 'Mcdowell', 'Wiley', 'Rich', 'Humphrey', 'Johns',
                'Koch', 'Suarez', 'Hobbs', 'Beard', 'Gilmore', 'Ibarra', 'Keith', 'Macias', 'Khan', 'Andrade', 'Ware',
                'Stephenson', 'Henson', 'Wilkerson', 'Dyer', 'Mcclure', 'Blackwell', 'Mercado', 'Tanner', 'Eaton',
                'Clay', 'Barron', 'Beasley', 'Oneal', 'Preston', 'Small', 'Wu', 'Zamora', 'Macdonald', 'Vance', 'Snow',
                'Mcclain', 'Stafford', 'Orozco', 'Barry', 'English', 'Shannon', 'Kline', 'Jacobson', 'Woodard', 'Huang',
                'Kemp', 'Mosley', 'Prince', 'Merritt', 'Hurst', 'Villanueva', 'Roach', 'Nolan', 'Lam', 'Yoder',
                'Mccullough', 'Lester', 'Santana', 'Valenzuela', 'Winters', 'Barrera', 'Leach', 'Orr', 'Berger',
                'Mckee', 'Strong', 'Conway', 'Stein', 'Whitehead', 'Bullock', 'Escobar', 'Knox', 'Meadows', 'Solomon',
                'Velez', 'Odonnell', 'Kerr', 'Stout', 'Blankenship', 'Browning', 'Kent', 'Lozano', 'Bartlett', 'Pruitt',
                'Buck', 'Barr', 'Gaines', 'Durham', 'Gentry', 'Mcintyre', 'Sloan', 'Melendez', 'Rocha', 'Herman',
                'Sexton', 'Moon', 'Hendricks', 'Rangel', 'Stark', 'Lowery', 'Hardin', 'Hull', 'Sellers', 'Ellison',
                'Calhoun', 'Gillespie', 'Mora', 'Knapp', 'Mccall', 'Morse', 'Dorsey', 'Weeks', 'Nielsen', 'Livingston',
                'Leblanc', 'Mclean', 'Bradshaw', 'Glass', 'Middleton', 'Buckley', 'Schaefer', 'Frost', 'Howe', 'House',
                'Mcintosh', 'Ho', 'Pennington', 'Reilly', 'Hebert', 'Mcfarland', 'Hickman', 'Noble', 'Spears', 'Conrad',
                'Arias', 'Galvan', 'Velazquez', 'Huynh', 'Frederick', 'Randolph', 'Cantu', 'Fitzpatrick', 'Mahoney',
                'Peck', 'Villa', 'Michael', 'Donovan', 'Mcconnell', 'Walls', 'Boyle', 'Mayer', 'Zuniga', 'Giles',
                'Pineda', 'Pace', 'Hurley', 'Mays', 'Mcmillan', 'Crosby', 'Ayers', 'Case', 'Bentley', 'Shepard',
                'Everett', 'Pugh', 'David', 'Mcmahon', 'Dunlap', 'Bender', 'Hahn', 'Harding', 'Acevedo', 'Raymond',
                'Blackburn', 'Duffy', 'Landry', 'Dougherty', 'Bautista', 'Shah', 'Potts', 'Arroyo', 'Valentine', 'Meza',
                'Gould', 'Vaughan', 'Fry', 'Rush', 'Avery', 'Herring', 'Dodson', 'Clements', 'Sampson', 'Tapia', 'Bean',
                'Lynn', 'Crane', 'Farley', 'Cisneros', 'Benton', 'Ashley', 'Mckay', 'Finley', 'Best', 'Blevins',
                'Friedman', 'Moses', 'Sosa', 'Blanchard', 'Huber', 'Frye', 'Krueger', 'Bernard', 'Rosario', 'Rubio',
                'Mullen', 'Benjamin', 'Haley', 'Chung', 'Moyer', 'Choi', 'Horne', 'Yu', 'Woodward', 'Ali', 'Nixon',
                'Hayden', 'Rivers', 'Estes', 'Mccarty', 'Richmond', 'Stuart', 'Maynard', 'Brandt', 'Oconnell', 'Hanna',
                'Sanford', 'Sheppard', 'Church', 'Burch', 'Levy', 'Rasmussen', 'Coffey', 'Ponce', 'Faulkner',
                'Donaldson', 'Schmitt', 'Novak', 'Costa', 'Montes', 'Booker', 'Cordova', 'Waller', 'Arellano', 'Maddox',
                'Mata', 'Bonilla', 'Stanton', 'Compton', 'Kaufman', 'Dudley', 'Mcpherson', 'Beltran', 'Dickson',
                'Mccann', 'Villegas', 'Proctor', 'Hester', 'Cantrell', 'Daugherty', 'Cherry', 'Bray', 'Davila',
                'Rowland', 'Levine', 'Madden', 'Spence', 'Good', 'Irwin', 'Werner', 'Krause', 'Petty', 'Whitney',
                'Baird', 'Hooper', 'Pollard', 'Zavala', 'Jarvis', 'Holden', 'Haas', 'Hendrix', 'Mcgrath', 'Bird',
                'Lucero', 'Terrell', 'Riggs', 'Joyce', 'Mercer', 'Rollins', 'Galloway', 'Duke', 'Odom', 'Andersen',
                'Downs', 'Hatfield', 'Benitez', 'Archer', 'Huerta', 'Travis', 'Mcneil', 'Hinton', 'Zhang', 'Hays',
                'Mayo', 'Fritz', 'Branch', 'Mooney', 'Ewing', 'Ritter', 'Esparza', 'Frey', 'Braun', 'Gay', 'Riddle',
                'Haney', 'Kaiser', 'Holder', 'Chaney', 'Mcknight', 'Gamble', 'Vang', 'Cooley', 'Carney', 'Cowan',
                'Forbes', 'Ferrell', 'Davies', 'Barajas', 'Shea', 'Osborn', 'Bright', 'Cuevas', 'Bolton', 'Murillo',
                'Lutz', 'Duarte', 'Kidd', 'Key', 'Cooke',
            ],
        ],
        'asian' => [
            'female' => ['none'],
            'male' => ['none'],
            'family' => [
                'Հովհաննիսյան', 'Հարությունյան', 'Սարգսյան', 'Խաչատրյան', 'Գրիգորյան',
                'আহমেদ', 'আলী', 'আক্তার', 'বন্দ্যোপাধ্যায়', 'নিক', 'ব্যাপারী', 'বড়ুয়া', 'বিশ্বাস', 'ভৌমিক', 'বসু', 
                '王', '李', '张', '刘', '陈', '杨', '黄', '赵', '吴', '周', '徐', '孙', '马', '朱', '胡', '郭', '何', '高', '林', '罗',
                'כהן', 'לוי', 'מזרחי', 'פרץ', 'ביטון', 'דהן', 'אברהם', 'פרידמן', 'מלכה', 'אזולאי', 'כץ', 'יוסף', 'דוד', 'עמר', 'אוחיון', 
                '김', '리', '박', '최', '정', '강', '조', '윤', '장', '림', '한', '신', '서', '권', '황', '안', '송', '홍', '고', '문', '손', '량', 
                'Yılmaz', 'Kaya', 'Demir', 'Şahin', 'Çelik', 'Yıldız', 'Yıldırım', 'Öztürk', 'Aydın', 'Özdemir', 'Arslan', 'Doğan', 'Kılıç', 'Aslan', 'Çetin', 'Kara', 'Koç', 'Kurt', 'Özkan', 'Şimşek', 
            ],
        ]
    ];



    /**
     * Get a random string.
     *
     * @param string[] $type   Name type (female, male, family)
     * @param string   $origin Name origin (western)
     *
     * @return string
     *
     * @since  1.0.0
     */
    public static function generateName(array $type, string $origin = 'western') : string
    {
        $rndType = mt_rand(0, count($type) - 1);

        return self::$names[$origin][$type[$rndType]][mt_rand(0, count(self::$names[$origin][$type[$rndType]]) - 1)];
    }
}
