<?php return [
    'some-hook-id-name:here' => [
        0 => '\some\function\to\call:functionname',
        1 => '\some\function\to\call:functionname',
        2 => '\some\function\to\call:functionname',
        3 => '\some\function\to\call:functionname',
        4 => '\some\function\to\call:functionname',
        5 => '\some\function\to\call:functionname',
        6 => '\some\function\to\call:functionname',
        7 => '\some\function\to\call:functionname',
        8 => '\some\function\to\call:functionname',
        9 => '\some\function\to\call:functionname',
        10 => '\some\function\to\call:functionname',
        11 => '\some\function\to\call:functionname',
        12 => '\some\function\to\call:functionname',
        13 => '\some\function\to\call:functionname',
        14 => '\some\function\to\call:functionname',
        15 => '\some\function\to\call:functionname',
        16 => '\some\function\to\call:functionname',
        17 => '\some\function\to\call:functionname',
        18 => '\some\function\to\call:functionname',
        19 => '\some\function\to\call:functionname',
    ],
];