name: CI

on:
  workflow_call:
    secrets:
      GH_TOKEN:
        required: true
      GH_PAT:
        required: true
      CODECOV_TOKEN:
        required: true

jobs:
  codestyle-tests:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'NO_CI')"
    steps:
    - name: Checkout Repository
      uses: actions/checkout@main
      with:
        fetch-depth: 0
        submodules: recursive
        token: ${{ secrets.GH_TOKEN }}
    - name: Checkout Build Repository
      uses: actions/checkout@main
      with:
          fetch-depth: 1
          ref: develop
          repository: Karaka-Management/Build
          path: Build
    - name: Copy config file
      run: |
        cp ./Build/Config/.clang-format ./.clang-format
    - name: Lint Code Base
      uses: super-linter/super-linter@v6.4.0
      env:
        VALIDATE_ALL_CODEBASE: false
        VALIDATE_CLANG_FORMAT : true
        DEFAULT_BRANCH: develop
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}