name: CI

on:
  workflow_call:
    secrets:
      DISCORD_HOOK:
        required: true

jobs:
  discord_message:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'NO_CI')"
    strategy:
        fail-fast: false
        max-parallel: 3
    steps:
      - uses: sarisia/actions-status-discord@v1
        if: always()
        with:
            webhook: ${{ secrets.DISCORD_HOOK }}