name: Image optimization
on:
  push:
  pull_request:
  workflow_call:
    secrets:
      GH_TOKEN:
        required: true
      GH_PAT:
        required: true

jobs:
  optimze:
    name: Image optimization
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@main
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Software installation
        run: |
          sudo apt-get install jpegoptim
          sudo apt-get install optipng
          sudo npm -g install svgo
      - name: Image optimization
        run: |
          find ./ -type f -name "*.png" -exec optipng '{}' \;
          find ./ -type f -name "*.jpg" -exec jpegoptim '{}' \;
          find ./ -type f -name "*.svg" -exec svgo {} \;
      - name: Check for modified files
        id: git-image-check
        run: echo "modified=$(if git diff-index --quiet HEAD --; then echo "false"; else echo "true"; fi)" >> $GITHUB_OUTPUT
      - name: Push changes
        if: steps.git-image-check.outputs.modified == 'true'
        run: |
          git config --global user.name 'Image Bot'
          git config --global user.email 'image.bot@jingga.app'
          git remote set-url origin https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/${{ github.repository }}
          git commit -am "Automated image optimization (NO_CI)"
          git push
