name: CI/CD

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: false
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: oms
        ports:
          - 3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    strategy:
      fail-fast: false
      max-parallel: 3
      matrix:
        php-versions: ['7.4']
    steps:
    - name: Checkout Repository
      uses: actions/checkout@master
    - name: Setup Submodules
      run: |
        git submodule update --init --recursive
        git submodule foreach git checkout develop
    - name: Setup PHP, with composer and extensions
      uses: shivammathur/setup-php@master
      with:
          php-version: ${{ matrix.php-versions }}
          extension-csv: mbstring, intl, gd, imagick, zip, dom, mysql
    - name: Setup Composer
      run: composer install
    - name: phpstan
      run: vendor/bin/phpstan analyse --autoload-file=phpOMS/Autoloader.php -l 7 -c Build/Config/phpstan.neon ./
    - name: phpcs
      run: vendor/bin/phpcs ./ --standard="Build/Config/phpcs.xml" -s --report=full
    - name: phpunit
      run: vendor/bin/phpunit --coverage-text -v --configuration tests/phpunit_no_coverage.xml
