name: CI/CD

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: true
          MYSQL_ROOT_PASSWORD: ""
          MYSQL_DATABASE: oms
        ports:
          - 3306
    steps:
    - name: Configure database
      run: mysql -u root -e "USE mysql; ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY ''; FLUSH PRIVILEGES;"
    - name: Checkout
      uses: actions/checkout@master
    - name: Setup submodules
      run: |
        git submodule update --init --recursive
        git submodule foreach git checkout develop
    - name: Setup composer
      run: composer install
    - name: Test with phpunit
      run: vendor/bin/phpunit --coverage-text -v --configuration tests/phpunit_default.xml
    - name: Test with phpstan
      run: /vendor/bin/phpstan --autoload-file=phpOMS/Autoloader.php -l 7 -c Build/Config/phpstan.neon ./
    - name: Test with phpcs
      run: /vendor/bin/phpcs ./ --standard="Build/Config/phpcs.xml" -s --report=full
